development: &default
  adapter: postgresql
  database: sf-openreferral_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: sf-openreferral_test
